@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

AddressBook *-right-> "1" UniquestudentList
AddressBook *-right-> "1" UniqueTagList
UniqueTagList -[hidden]down- UniquestudentList
UniqueTagList -[hidden]down- UniquestudentList

UniqueTagList -right-> "*" Tag
UniquestudentList -right-> student

student -up-> "*" Tag

student *--> Name
student *--> Phone
student *--> Email
student *--> Address
@enduml
